### ISSUE TITLE
[Bug]: Unexpected behavior of command Reminder: Toggle checklist status

### ISSUE THREAD

**Issue by joellti** [uphy/obsidian-reminder#116]
### Describe the bug

When running it to a recurring tasks, command `Reminder: Toggle checklist status` sometimes sets the time wrong in the new recurrence. Like the one below.

Before `Reminder: Toggle checklist status` is run:

- [ ] test ⏰ 2022-11-04 9:00 🔁 every week 📅 2022-11-04

After:

- [ ] test ⏰ 2022-11-11 08:00 🔁 every week 📅 2022-11-10
- [x] test ⏰ 2022-11-04 9:00 🔁 every week 📅 2022-11-04 ✅ 2022-11-03

As you can see above, the time in the new entry is changed from 9:00 to 8:00. I assume it's not intended behavior.

### Steps to reproduce

See above

### Operating system

Windows
